### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by solbadguy2010** [valiquette/homebridge-easee#15]
Hi, i receive these errors in my log since some days...

[17/03/2023, 11:09:18] [Easee] Token has been refreshed
[17/03/2023, 11:09:24] [Easee] SignalR has been reset
[17/03/2023, 11:09:24] [Easee] SignalR has been reset
[17/03/2023, 11:09:24] [Easee] Error while starting connection: AbortError: Failed to start the HttpConnection before stop() was called.
    at HttpConnection.start (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:148:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HubConnection._startInternal (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:207:9)
    at HubConnection._startWithStateTransitions (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:181:13)
[17/03/2023, 11:09:24] [Easee] Starting connection for live updates...
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 cable lock state to true
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 updated to ChargerOpMode Disconnected
[17/03/2023, 11:09:24] [Easee] Weiss disconnected
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 OutputCurrent updated to 0
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 DynamicChargerCurrent updated to 32
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 ReasonForNoCurrent due to SecondaryUnitNotRequestingCurrent
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 AuthorizationRequired updated to false
[17/03/2023, 11:09:24] [Easee] EHQYX6R7 MaxChargerCurrent updated to 20

**Comment by valiquette** [comment]
How often has this error shown? and what version was this under? The error seems like the plugin handled it fine so no concern with seeing it in the log if it is a one off. This latest version will establish a new connection once a day, and close the old connection. Some of the recent beta version were not addressing this correctly.

**Comment by solbadguy2010** [comment]
Its the most recent, non beta, version. It happens multiple times. I ignored it the first 5 to 7 times i sae it :-)

**Comment by valiquette** [comment]
Thanks for reporting, I have one similar error in my logs, not exactly the same but close. I will have to keep an eye out for this. With some of these new updates I am now logging more than before, these errors may have always been there just not logged.

**Comment by Nastras** [comment]
Hello @valiquette, 
i hope you are well?

I also get an error message in the jornalctl/log since a short time. Can you do anything with it?

`Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]: [Easee] Error while starting connection: FailedToNegotiateWithServerError: Failed to complete negotiation with the server: Error: {"message":"Forbidden"}: Status code '403'
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HttpConnection._getNegotiationResponse (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:346:35)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HttpConnection._startInternal (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:247:41) {
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:   errorType: 'FailedToNegotiateWithServerError'
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]: }
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]: [Easee] Error while starting connection: FailedToNegotiateWithServerError: Failed to complete negotiation with the server: Error: {"message":"Forbidden"}: Status code '403'
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HttpConnection._getNegotiationResponse (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:346:35)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HttpConnection._startInternal (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:247:41)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HttpConnection.start (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HttpConnection.ts:137:9)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HubConnection._startInternal (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:207:9)
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:     at HubConnection._startWithStateTransitions (/usr/local/lib/node_modules/homebridge-easee/node_modules/@microsoft/signalr/src/HubConnection.ts:181:13) {
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]:   errorType: 'FailedToNegotiateWithServerError'
Mai 21 08:52:35 Ak-SHS-1 homebridge[15114]: }
Mai 21 08:52:39 Ak-SHS-1 homebridge[15114]: [Easee] Easee Platform finished loading
`

<img width="1424" alt="Bildschirmfoto 2023-05-21 um 08 56 02" src="https://github.com/valiquette/homebridge-easee/assets/27686185/436589d7-c1a9-49ab-81db-901630eb3db6">


Regards
Nastras

**Comment by valiquette** [comment]
This is usually a network issue of some sort, it will retry a few times. Is this happening on every restart?

**Comment by Nastras** [comment]
`The problem persists even after restarting homebridge several times. `
I am surprised because I have not changed anything in my network.

`Is this happening on every restart? `
Yes 😅

**Comment by valiquette** [comment]
Can you provide a token for me to look into this. Microsoft released update to signalR and they are working on new version so something could be up with this. The 403 error does seem different from network error.

**Comment by Nastras** [comment]
I sent you a Whats App.
Has it arrived?

**Comment by valiquette** [comment]
https://developer.easee.cloud/docs/integrations-30
https://developer.easee.cloud/changelog/signalr-uri-change

The plugin did not like the signalR change. 
if you can confirm the latest version is ok, I'll close the issue

**Comment by Nastras** [comment]
Hey @valiquette,
Everything works again. Thanks a lot! Good job!
