### ISSUE TITLE
Does this need to be a lock?

### ISSUE THREAD

**Issue by solbadguy2010** [valiquette/homebridge-easee#2]
Hi.
Thank you for this plugin. It works great. I was just wondering if this device really needs to be a lock in homekit?
I would like to set up an automation that the easee is locked when we leave home and unlock if someone is at home. Sadly unlocking is not working with an automatism sinse a lock is a security device and needs approval. If this simply would be a switch there wouldn't be a problem.

Thank you

Timo

**Comment by valiquette** [comment]
It does not, but it seemed to make the most sense where you want to restrict access. I originally wrote the plugin for a Wallbox brand charger for use outside and locking it is exactly what it does. 
Your use case is the same as mine. What I would try this work around for HomeKit. Create a new scene and add the charger lock to it as unlocked. then run you automation against that scene instead of the lock directly. This should do what you want. If you already have scenes for home and away you can add the open lock or close lock to those and it too should work.

**Comment by solbadguy2010** [comment]
Ok. Understand. I will test. Is the type hard to change? Maybe its possible to let the users choose if this is a lock, switch or light? :-)

**Comment by valiquette** [comment]
The different types do not use the same characteristics so it would not be a simple change. With a lock the target state can be set and you wait for a response back to show it as locked or still unlocked, with a switch or outlet it is just on or off. If the automation work around does not work I can look into this.

**Comment by valiquette** [comment]
I may be able to add an the option to add an outlet to the lock which could enable/disable the authorization. You could just run the automation against the outlet. There is already a switch and lightbulb adding another one of those would add more complication.

**Comment by valiquette** [comment]
Did a scene give you what you needed or do I need to look at this as a feature request?

**Comment by solbadguy2010** [comment]
Works :-)
